# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_vulkanR_wrappers", use_symbols = TRUE, package_name = "vulkanR")

#' @docType package
#' @usage NULL
#' @useDynLib vulkanR, .registration = TRUE
NULL

# The high-level R APIs are defined in `api.R`.  Only the registration block
# generated by extendr is required here so the native symbols are available to
# `.Call` from those wrappers.


# nolint end
