# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_vulkanR_wrappers", use_symbols = TRUE, package_name = "vulkanR")

#' @docType package
#' @usage NULL
#' @useDynLib vulkanR, .registration = TRUE
NULL

#' Get GPU information
gpu_info <- function() .Call(wrap__gpu_info)

#' Render heightmap to PNG
render_heightmap <- function(path, z, width, height, scale_z, fov_deg, sun_dir) .Call(wrap__render_heightmap, path, z, width, height, scale_z, fov_deg, sun_dir)


# nolint end
